export const GET_CATEGORY = "GET_CATEGORY"
export const GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING"
export const GET_CATEGORY_FULFILLED = "GET_CATEGORY_FULFILLED"
export const GET_CATEGORY_REJECTED = "GET_CATEGORY_REJECTED"

export const GET_EVENTBYCATEGORY = "GET_EVENTBYCATEGORY"
export const GET_EVENTBYCATEGORY_PENDING = "GET_EVENTBYCATEGORY_PENDING"
export const GET_EVENTBYCATEGORY_FULFILLED = "GET_EVENTBYCATEGORY_FULFILLED"
export const GET_EVENTBYCATEGORY_REJECTED = "GET_EVENTBYCATEGORY_REJECTED"

export const GET_EVENT = "GET_EVENT"
export const GET_EVENT_PENDING = "GET_EVENT_PENDING"
export const GET_EVENT_FULFILLED = "GET_EVENT_FULFILLED"
export const GET_EVENT_REJECTED = "GET_EVENT_REJECTED"

export const GET_EVENTBYID = "GET_EVENTBYID"
export const GET_EVENTBYID_PENDING = "GET_EVENTBYID_PENDING"
export const GET_EVENTBYID_FULFILLED = "GET_EVENTBYID_FULFILLED"
export const GET_EVENTBYID_REJECTED = "GET_EVENTBYID_REJECTED"

export const LOGIN = "LOGIN"
export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_FULFILLED = "LOGIN_FULFILLED"
export const LOGIN_REJECTED = "LOGIN_REJECTED"

export const GET_USERBYID = "GET_USERBYID"
export const GET_USERBYID_PENDING = "GET_USERBYID_PENDING"
export const GET_USERBYID_FULFILLED = "GET_USERBYID_FULFILLED"
export const GET_USERBYID_REJECTED = "GET_USERBYID_REJECTED"

export const GET_CATEGORYBYID = "GET_CATEGORYBYID"
export const GET_CATEGORYBYID_PENDING = "GET_CATEGORYBYID_PENDING"
export const GET_CATEGORYBYID_FULFILLED = "GET_CATEGORYBYID_FULFILLED"
export const GET_CATEGORYBYID_REJECTED = "GET_CATEGORYBYID_REJECTED"

export const GET_PAYMENT = "GET_PAYMENT"
export const GET_PAYMENT_PENDING = "GET_PAYMENT_PENDING"
export const GET_PAYMENT_FULFILLED = "GET_PAYMENT_FULFILLED"
export const GET_PAYMENT_REJECTED = "GET_PAYMENT_REJECTED"

export const GET_APPROVEDPAYMENT = "GET_APPROVEDPAYMENT"
export const GET_APPROVEDPAYMENT_PENDING = "GET_APPROVEDPAYMENT_PENDING"
export const GET_APPROVEDPAYMENT_FULFILLED = "GET_APPROVEDPAYMENT_FULFILLED"
export const GET_APPROVEDPAYMENT_REJECTED = "GET_APPROVEDPAYMENT_REJECTED"

export const GET_FAVORITE = "GET_FAVORITE"
export const GET_FAVORITE_PENDING = "GET_FAVORITE_PENDING"
export const GET_FAVORITE_FULFILLED = "GET_FAVORITE_FULFILLED"
export const GET_FAVORITE_REJECTED = "GET_FAVORITE_REJECTED"